# Starship configuration for Zsh on macOS (Bash-like prompt)
# Place this file as starship.toml in your home directory or reference it in your setup script

[character]
success_symbol = "[\$](bold green) "
error_symbol = "[\$](bold red) "

[username]
disabled = false
show_always = true
style_user = "bold yellow"

[hostname]
disabled = false
ssh_only = false
style = "bold cyan"

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = ".../"

[shell]
disabled = false

# Show git branch if in repo
[git_branch]
disabled = false
style = "bold purple"

# Show git status if in repo
[git_status]
disabled = false
style = "bold red"

# Show time
[time]
disabled = false
format = "[$time]($style) "
style = "bold white"

# Remove extra modules for minimal bash-like look
[package]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[rust]
disabled = true

# Example prompt order (similar to bash):
format = "$username@$hostname $directory $git_branch $git_status $time $character"
